# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DAY_OF_WEEK: Monday

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Talent
          MIDDLE_NAME: Agile
          LAST_NAME: Accelerate
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME $DAY_OF_WEEK $GREETING
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
