# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  issues:
    types:
      - opened
env:
  DAY_OF_WEEK: Tuesday

jobs:
  my-job:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}
    env:
      Greeting: Hello
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Talent
          MIDDLE_NAME: Agile
          LAST_NAME: Accelerate
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME $DAY_OF_WEEK $GREETING
          echo "::debug::Set the Octocat variable"
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Monday' }}
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
